version: '3.8'

services:
  app:
    build: .
    container_name: pucem-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
